<?php 

return [
    "vi" => [
        "view_mode_notes" => "Chọn chế độ xem bạn thích để có trải nghiệm thoải mái hơn nhé!",
        "light_mode" => "Chế độ sáng",
        "gray_mode" => "Chế độ xám",
        "sepia_mode" => "Chế độ nâu ấm",
        "dark_mode" => "Chế độ tối",
    ],
    "en" => [
        "view_mode_notes" => "Choose the view mode you like for a more comfortable experience!",
        "light_mode" => "Light mode",
        "gray_mode" => "Gray mode",
        "sepia_mode" => "Sepia mode",
        "dark_mode" => "Dark mode",
    ],
    "zh" => [
        "view_mode_notes" => "选择您喜欢的查看模式，享受更舒适的体验！",
        "light_mode" => "明亮模式",
        "gray_mode" => "灰色模式",
        "sepia_mode" => "棕褐色模式",
        "dark_mode" => "深色模式",
    ],
    "es" => [
        "view_mode_notes" => "¡Elige el modo de visualización que prefieras para una experiencia más cómoda!",
        "light_mode" => "Modo claro",
        "gray_mode" => "Modo gris",
        "sepia_mode" => "Modo sepia",
        "dark_mode" => "Modo oscuro",
    ],
    "fr" => [
        "view_mode_notes" => "Choisissez le mode d'affichage que vous aimez pour une expérience plus confortable !",
        "light_mode" => "Mode clair",
        "gray_mode" => "Mode gris",
        "sepia_mode" => "Mode sépia",
        "dark_mode" => "Mode sombre",
    ],
    "hi" => [
        "view_mode_notes" => "अपनी पसंद का व्यू मोड चुनें ताकि आपका अनुभव और आरामदायक हो!",
        "light_mode" => "हल्का मोड",
        "gray_mode" => "ग्रे मोड",
        "sepia_mode" => "सेपिया मोड",
        "dark_mode" => "डार्क मोड",
    ],
    "bn" => [
        "view_mode_notes" => "আপনার পছন্দের দৃশ্য মোড নির্বাচন করুন আরও আরামদায়ক অভিজ্ঞতার জন্য!",
        "light_mode" => "হালকা মোড",
        "gray_mode" => "ধূসর মোড",
        "sepia_mode" => "সেপিয়া মোড",
        "dark_mode" => "অন্ধকার মোড",
    ],
    "mr" => [
        "view_mode_notes" => "आपल्याला हवा तसा दृश्य मोड निवडा, जेणेकरून अनुभव अधिक आरामदायक होईल!",
        "light_mode" => "हलका मोड",
        "gray_mode" => "राखाडी मोड",
        "sepia_mode" => "सिपिया मोड",
        "dark_mode" => "गडद मोड",
    ],
    "ta" => [
        "view_mode_notes" => "நீங்கள் விரும்பும் காட்சி முறையைத் தேர்ந்தெடுங்கள், மிகவும் வசதியான அனுபவத்திற்கு!",
        "light_mode" => "வெளிர் முறை",
        "gray_mode" => "சாம்பல் முறை",
        "sepia_mode" => "செப்பியா முறை",
        "dark_mode" => "இருண்ட முறை",
    ],
    "te" => [
        "view_mode_notes" => "మీకు నచ్చిన వీక్షణ మోడ్‌ను ఎంచుకోండి, మరింత సౌకర్యవంతమైన అనుభవం కోసం!",
        "light_mode" => "లైట్ మోడ్",
        "gray_mode" => "గ్రే మోడ్",
        "sepia_mode" => "సీపియా మోడ్",
        "dark_mode" => "డార్క్ మోడ్",
    ],
    "ur" => [
        "view_mode_notes" => "اپنی پسند کا منظر موڈ منتخب کریں تاکہ زیادہ آرام دہ تجربہ حاصل ہو!",
        "light_mode" => "ہلکا موڈ",
        "gray_mode" => "سرمئی موڈ",
        "sepia_mode" => "سیپیا موڈ",
        "dark_mode" => "گہرا موڈ",
    ],
    "gu" => [
        "view_mode_notes" => "તમને ગમતું દૃશ્ય મોડ પસંદ કરો જેથી વધુ આરામદાયક અનુભવ મળે!",
        "light_mode" => "હલકું મોડ",
        "gray_mode" => "ગ્રે મોડ",
        "sepia_mode" => "સેપિયા મોડ",
        "dark_mode" => "ડાર્ક મોડ",
    ],
    "ja" => [
        "view_mode_notes" => "快適な体験のために、好きな表示モードを選んでください！",
        "light_mode" => "ライトモード",
        "gray_mode" => "グレーモード",
        "sepia_mode" => "セピアモード",
        "dark_mode" => "ダークモード",
    ],
    "ko" => [
        "view_mode_notes" => "더 편안한 경험을 위해 원하는 보기 모드를 선택하세요!",
        "light_mode" => "라이트 모드",
        "gray_mode" => "그레이 모드",
        "sepia_mode" => "세피아 모드",
        "dark_mode" => "다크 모드",
    ],
    "jv" => [
        "view_mode_notes" => "Pilih mode tampilan sing sampeyan senengi supaya pengalaman luwih nyaman!",
        "light_mode" => "Mode cahya",
        "gray_mode" => "Mode abu-abu",
        "sepia_mode" => "Mode sepia",
        "dark_mode" => "Mode peteng",
    ],
    "id" => [
        "view_mode_notes" => "Pilih mode tampilan yang Anda suka untuk pengalaman yang lebih nyaman!",
        "light_mode" => "Mode terang",
        "gray_mode" => "Mode abu-abu",
        "sepia_mode" => "Mode sepia",
        "dark_mode" => "Mode gelap",
    ],
    "ms" => [
        "view_mode_notes" => "Pilih mod paparan yang anda suka untuk pengalaman yang lebih selesa!",
        "light_mode" => "Mod terang",
        "gray_mode" => "Mod kelabu",
        "sepia_mode" => "Mod sepia",
        "dark_mode" => "Mod gelap",
    ],
    "th" => [
        "view_mode_notes" => "เลือกโหมดการแสดงผลที่คุณชอบเพื่อประสบการณ์ที่สะดวกสบายยิ่งขึ้น!",
        "light_mode" => "โหมดสว่าง",
        "gray_mode" => "โหมดเทา",
        "sepia_mode" => "โหมดเซเปีย",
        "dark_mode" => "โหมดมืด",
    ],
    "ar" => [
        "view_mode_notes" => "اختر وضع العرض الذي تفضله لتجربة أكثر راحة!",
        "light_mode" => "وضع فاتح",
        "gray_mode" => "وضع رمادي",
        "sepia_mode" => "وضع سيبيا",
        "dark_mode" => "وضع داكن",
    ],
    "fa" => [
        "view_mode_notes" => "حالت نمایش مورد علاقه خود را انتخاب کنید تا تجربه‌ای راحت‌تر داشته باشید!",
        "light_mode" => "حالت روشن",
        "gray_mode" => "حالت خاکستری",
        "sepia_mode" => "حالت سپیا",
        "dark_mode" => "حالت تیره",
    ],
    "ru" => [
        "view_mode_notes" => "Выберите режим отображения, который вам нравится, для более комфортного опыта!",
        "light_mode" => "Светлый режим",
        "gray_mode" => "Серый режим",
        "sepia_mode" => "Режим сепия",
        "dark" => "Темный режим",
    ],
    "de" => [
        "view_mode_notes" => "Wählen Sie den Anzeigemodus, der Ihnen gefällt, für ein angenehmeres Erlebnis!",
        "light_mode" => "Heller Modus",
        "gray_mode" => "Grauer Modus",
        "sepia_mode" => "Sepia-Modus",
        "dark_mode" => "Dunkler Modus",
    ],
    "tr" => [
        "view_mode_notes" => "Daha rahat bir deneyim için istediğiniz görüntüleme modunu seçin!",
        "light_mode" => "Açık mod",
        "gray_mode" => "Gri mod",
        "sepia_mode" => "Sepya mod",
        "dark_mode" => "Koyu mod",
    ],
    "it" => [
        "view_mode_notes" => "Scegli la modalità di visualizzazione che preferisci per un'esperienza più confortevole!",
        "light_mode" => "Modalità chiara",
        "gray_mode" => "Modalità grigia",
        "sepia_mode" => "Modalità seppia",
        "dark_mode" => "Modalità scura",
    ],
    "pl" => [
        "view_mode_notes" => "Wybierz tryb wyświetlania, który Ci się podoba, aby uzyskać wygodniejsze doświadczenie!",
        "light_mode" => "Tryb jasny",
        "gray_mode" => "Tryb szary",
        "sepia_mode" => "Tryb sepia",
        "dark_mode" => "Tryb ciemny",
    ],
    "uk" => [
        "view_mode_notes" => "Виберіть режим відображення, який вам подобається, для комфортнішого досвіду!",
        "light_mode" => "Світлий режим",
        "gray_mode" => "Сірий режим",
        "sepia_mode" => "Режим сепія",
        "dark_mode" => "Темний режим",
    ],
    "nl" => [
        "view_mode_notes" => "Kies de weergavemodus die je voorkeur heeft voor een comfortabelere ervaring!",
        "light_mode" => "Lichte modus",
        "gray_mode" => "Grijze modus",
        "sepia_mode" => "Sepia modus",
        "dark_mode" => "Donkere modus",
    ],
    "el" => [
        "view_mode_notes" => "Επιλέξτε τη λειτουργία προβολής που σας αρέσει για μια πιο άνετη εμπειρία!",
        "light_mode" => "Ανοιχτή λειτουργία",
        "gray_mode" => "Γκρι λειτουργία",
        "sepia_mode" => "Λειτουργία σέπια",
        "dark_mode" => "Σκοτεινή λειτουργία",
    ],
    "hu" => [
        "view_mode_notes" => "Válaszd ki a neked tetsző megjelenítési módot a kényelmesebb élmény érdekében!",
        "light_mode" => "Világos mód",
        "gray_mode" => "Szürke mód",
        "sepia_mode" => "Sépia mód",
        "dark_mode" => "Sötét mód",
    ],
    "cs" => [
        "view_mode_notes" => "Vyberte si režim zobrazení, který se vám líbí, pro pohodlnější zážitek!",
        "light_mode" => "Světlý režim",
        "gray_mode" => "Šedý režim",
        "sepia_mode" => "Sépiový režim",
        "dark_mode" => "Tmavý režim",
    ],
    "ro" => [
        "view_mode_notes" => "Alege modul de afișare care îți place pentru o experiență mai confortabilă!",
        "light_mode" => "Mod luminos",
        "gray_mode" => "Mod gri",
        "sepia_mode" => "Mod sepia",
        "dark_mode" => "Mod întunecat",
    ],
    "sk" => [
        "view_mode_notes" => "Vyberte si režim zobrazenia, ktorý sa vám páči, pre pohodlnejší zážitok!",
        "light_mode" => "Svetlý režim",
        "gray_mode" => "Sivý režim",
        "sepia_mode" => "Sépiový režim",
        "dark_mode" => "Tmavý režim",
    ],
    "ka" => [
        "view_mode_notes" => "აირჩიეთ ჩვენების რეჟიმი, რომელიც მოგწონთ, უფრო კომფორტული გამოცდილებისთვის!",
        "light_mode" => "ღია რეჟიმი",
        "gray_mode" => "ნაცრისფერი რეჟიმი",
        "sepia_mode" => "სეპიის რეჟიმი",
        "dark_mode" => "მუქი რეჟიმი",
    ],
    "he" => [
        "view_mode_notes" => "בחר את מצב התצוגה שאתה מעדיף לחוויה נוחה יותר!",
        "light_mode" => "מצב בהיר",
        "gray_mode" => "מצב אפור",
        "sepia_mode" => "מצב ספיה",
        "dark_mode" => "מצב כהה",
    ],
    "uz" => [
        "view_mode_notes" => "Qulayroq tajriba uchun o‘zingizga yoqadigan ko‘rish rejimini tanlang!",
        "light_mode" => "Yorqin rejim",
        "gray_mode" => "Kulrang rejim",
        "sepia_mode" => "Sepiya rejimi",
        "dark_mode" => "Qorong‘u rejim",
    ],
    "pt" => [
        "view_mode_notes" => "Escolha o modo de visualização que preferir para uma experiência mais confortável!",
        "light_mode" => "Modo claro",
        "gray_mode" => "Modo cinza",
        "sepia_mode" => "Modo sépia",
        "dark_mode" => "Modo escuro",
    ],
    "fil" => [
        "view_mode_notes" => "Piliin ang mode ng pagtingin na gusto mo para sa mas komportableng karanasan!",
        "light_mode" => "Light mode",
        "gray_mode" => "Gray mode",
        "sepia_mode" => "Sepia mode",
        "dark_mode" => "Dark mode",
    ],
    "sv" => [
        "view_mode_notes" => "Välj det visningsläge du gillar för en mer bekväm upplevelse!",
        "light_mode" => "Ljust läge",
        "gray_mode" => "Grått läge",
        "sepia_mode" => "Sepia läge",
        "dark_mode" => "Mörkt läge",
    ],
    "no" => [
        "view_mode_notes" => "Velg visningsmodus du liker for en mer komfortabel opplevelse!",
        "light_mode" => "Lys modus",
        "gray_mode" => "Grå modus",
        "sepia_mode" => "Sepia modus",
        "dark_mode" => "Mørk modus",
    ],
    "fi" => [
        "view_mode_notes" => "Valitse haluamasi näyttötila mukavamman kokemuksen saamiseksi!",
        "light_mode" => "Vaalea tila",
        "gray_mode" => "Harmaa tila",
        "sepia_mode" => "Sepia-tila",
        "dark_mode" => "Tumma tila",
    ],
    "da" => [
        "view_mode_notes" => "Vælg den visningstilstand, du foretrækker, for en mere behagelig oplevelse!",
        "light_mode" => "Lys tilstand",
        "gray_mode" => "Grå tilstand",
        "sepia_mode" => "Sepia-tilstand",
        "dark_mode" => "Mørk tilstand",
    ],
    "ml" => [
        "view_mode_notes" => "നിനക്ക് ഇഷ്ടമുള്ള വ്യൂ മോഡ് തിരഞ്ഞെടുക്കൂ, കൂടുതൽ സുഖകരമായ അനുഭവത്തിനായി!",
        "light_mode" => "ലൈറ്റ് മോഡ്",
        "gray_mode" => "ഗ്രേ മോഡ്",
        "sepia_mode" => "സെപിയ മോഡ്",
        "dark_mode" => "ഡാർക്ക് മോഡ്",
    ],
    "bg" => [
        "view_mode_notes" => "Изберете режима на изглед, който харесвате, за по-удобно изживяване!",
        "light_mode" => "Светъл режим",
        "gray_mode" => "Сив режим",
        "sepia_mode" => "Сепия режим",
        "dark_mode" => "Тъмен режим",
    ],
    "ky" => [
        "view_mode_notes" => "Өзүңүзгө жаккан көрүү режимин тандаңыз, ыңгайлуу тажрыйба үчүн!",
        "light_mode" => "Жарык режим",
        "gray_mode" => "Боз режим",
        "sepia_mode" => "Сепия режими",
        "dark_mode" => "Караңгы режим",
    ],
    "sr" => [
        "view_mode_notes" => "Изаберите режим приказа који вам се свиђа за угодније искуство!",
        "light_mode" => "Светли режим",
        "gray_mode" => "Сиви режим",
        "sepia_mode" => "Сепија режим",
        "dark_mode" => "Тамни режим",
    ],
    "lv" => [
        "view_mode_notes" => "Izvēlieties skata režīmu, kas jums patīk, lai iegūtu ērtāku pieredzi!",
        "light_mode" => "Gaišais režīms",
        "gray_mode" => "Pelēkais režīms",
        "sepia_mode" => "Sēpijas režīms",
        "dark_mode" => "Tumšais režīms",
    ],
    "lt" => [
        "view_mode_notes" => "Pasirinkite peržiūros režimą, kuris jums patinka, kad patirtis būtų patogesnė!",
        "light_mode" => "Šviesus režimas",
        "gray_mode" => "Pilkas režimas",
        "sepia_mode" => "Sepijos režimas",
        "dark_mode" => "Tamsus režimas",
    ],
    "sl" => [
        "view_mode_notes" => "Izberite način prikaza, ki vam je všeč, za bolj udobno izkušnjo!",
        "light_mode" => "Svetli način",
        "gray_mode" => "Sivi način",
        "sepia_mode" => "Sepia način",
        "dark_mode" => "Temni način",
    ],
    "mn" => [
        "view_mode_notes" => "Танд таалагддаг харах горимыг сонгоод илүү тухтай туршлага аваарай!",
        "light_mode" => "Гэрлийн горим",
        "gray_mode" => "Саарал горим",
        "sepia_mode" => "Сепиа горим",
        "dark_mode" => "Харанхуй горим",
    ],
];