<?php

return [
    "vi"    => [
        "name"      => "Việt",
        "currency"  => "VNĐ",
        "money_value"     => "23000",
        "key"       => "vi",
        "data"      => [
            "home"              => "Trang chủ",
            "about_us"          => "Về chúng tôi",
            "wallpaper_theme"   => "Chủ đề Hình Nền",
            "wallpaper_style"   => "Phong cách Hình Nền",
            "event"             => "Sự kiện",
            "free_wallpaper"    => "Hình nền Miễn Phí",
            "support"           => "Hỗ trợ",
            "connect_with_us"   => "Kết nối với chúng tôi",
            "table_of_contents" => "Mục lục",
            "photo_set"         => "Bộ ảnh",
            "share"             => "Chia sẻ",
            "no_suitable_results_found" => "Không có kết quả phù hợp",
            "cart"              => "Giỏ hàng",
            "your_cart_is_empty"    => "Giỏ hàng của bạn trống",
            "continue_shopping"     => "Tiếp tục mua sắm",
            "phone_wallpaper"         => "Hình nền điện thoại ",
        ]
    ],
    "en"    => [
        "name"  => "Anh",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "en",
        "data"      => [
            "home"          => "Home",
            "about_us"      => "About us",
            "wallpaper_theme"  => "Wallpaper Theme",
            "wallpaper_style"   => "Wallpaper Style",
            "event"             => "Event",
            "free_wallpaper"    => "Free Wallpaper",
            "support"           => "Support",
            "connect_with_us"   => "Connect with us",
            "table_of_contents" => "Table of Contents",
            "photo_set"         => "Photo set",
            "share"             => "Share",
            "no_suitable_results_found" => "No suitable results found",
            "cart"              => "Cart",
            "your_cart_is_empty"    => "Your cart is empty",
            "continue_shopping"     => "Continue shopping",
            "phone_wallpaper"         => "Phone Wallpaper ",
        ]
    ],
    "fr"    => [
        "name"  => "Pháp",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "fr",
        "data"      => [
            "home"          => "Accueil",
            "about_us"      => "À propos de nous",
            "wallpaper_theme"  => "Thème de fond d'écran",
            "wallpaper_style"   => "Style de fond d'écran",
            "event"             => "Événement",
            "free_wallpaper"    => "Fond d'écran gratuit",
            "support"           => "Support",
            "connect_with_us"   => "Connectez-vous avec nous",
            "table_of_contents" => "Table des matières",
            "photo_set"         => "Série de photos",
            "share"             => "Partager",
            "no_suitable_results_found" => "Aucun résultat approprié trouvé",
            "cart"              => "Panier",
            "your_cart_is_empty"    => "Votre panier est vide",
            "continue_shopping"     => "Continuer les achats",
            "phone_wallpaper"         => "Fond d'écran de téléphone ",
        ]
    ],
    "es"    => [
        "name"  => "Tây Ban Nha",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "es",
        "data"      => [
            "home"          => "Inicio",
            "about_us"      => "Sobre nosotros",
            "wallpaper_theme"  => "Tema de fondo de pantalla",
            "wallpaper_style"   => "Estilo de fondo de pantalla",
            "event"             => "Evento",
            "free_wallpaper"    => "Fondo de pantalla gratis",
            "support"           => "Soporte",
            "connect_with_us"   => "Conéctate con nosotros",
            "table_of_contents" => "Tabla de contenido",
            "photo_set"         => "Conjunto de fotos",
            "share"             => "Compartir",
            "no_suitable_results_found" => "No se encontraron resultados adecuados",
            "cart"              => "Carrito",
            "your_cart_is_empty"    => "Tu carrito está vacío",
            "continue_shopping"     => "Continuar comprando",
            "phone_wallpaper"         => "Fondo de pantalla del teléfono ",
        ]
    ],
    "cn"    => [
        "name"  => "Trung Quốc (Quan Thoại)",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "cn",
        "data"      => [
            "home"          => "首页",
            "about_us"      => "关于我们",
            "wallpaper_theme"  => "壁纸主题",
            "wallpaper_style"   => "壁纸风格",
            "event"             => "事件",
            "free_wallpaper"    => "免费壁纸",
            "support"           => "支持",
            "connect_with_us"   => "与我们联系",
            "table_of_contents" => "目录",
            "photo_set"         => "照片集",
            "share"             => "分享",
            "no_suitable_results_found" => "没有找到合适的结果",
            "cart"              => "购物车",
            "your_cart_is_empty"    => "您的购物车是空的",
            "continue_shopping"     => "继续购物",
            "phone_wallpaper"         => "手机壁纸",
        ]
    ],
    "ru"    => [
        "name"  => "Nga",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "ru",
        "data"      => [
            "home"          => "Главная",
            "about_us"      => "О нас",
            "wallpaper_theme"  => "Тема обоев",
            "wallpaper_style"   => "Стиль обоев",
            "event"             => "Событие",
            "free_wallpaper"    => "Бесплатный обои",
            "support"           => "Поддержка",
            "connect_with_us"   => "Свяжитесь с нами",
            "table_of_contents" => "Оглавление",
            "photo_set"         => "Фотосет",
            "share"             => "Поделиться",
            "no_suitable_results_found" => "Подходящих результатов не найдено",
            "cart"              => "Корзина",
            "your_cart_is_empty"    => "Ваша корзина пуста",
            "continue_shopping"     => "Продолжить покупки",
            "phone_wallpaper"         => "Обои для телефона ",
        ]
    ],
    "ja"    => [
        "name"  => "Nhật Bản",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "ja",
        "data"      => [
            "home"          => "ホーム",
            "about_us"      => "私たちについて",
            "wallpaper_theme"  => "壁紙のテーマ",
            "wallpaper_style"   => "壁紙のスタイル",
            "event"             => "イベント",
            "free_wallpaper"    => "無料壁紙",
            "support"           => "サポート",
            "connect_with_us"   => "私たちとつながる",
            "table_of_contents" => "目次",
            "photo_set"         => "写真セット",
            "share"             => "共有",
            "no_suitable_results_found" => "適切な結果が見つかりませんでした",
            "cart"              => "カート",
            "your_cart_is_empty"    => "カートは空です",
            "continue_shopping"     => "買い物を続ける",
            "phone_wallpaper"         => "電話の壁紙",
        ]
    ],
    "ko"    => [
        "name"  => "Hàn Quốc",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "ko",
        "data"      => [
            "home"          => "홈",
            "about_us"      => "우리에 관하여",
            "wallpaper_theme"  => "벽지 테마",
            "wallpaper_style"   => "벽지 스타일",
            "event"             => "이벤트",
            "free_wallpaper"    => "무료 배경 화면",
            "support"           => "지원",
            "connect_with_us"   => "우리와 연락",
            "table_of_contents" => "목차",
            "photo_set"         => "사진 세트",
            "share"             => "공유",
            "no_suitable_results_found" => "적합한 결과를 찾을 수 없습니다",
            "cart"              => "카트",
            "your_cart_is_empty"    => "장바구니가 비어 있습니다",
            "continue_shopping"     => "쇼핑 계속하기",
            "phone_wallpaper"         => "휴대폰 배경화면 ",
        ]
    ],
    "hi"    => [
        "name"  => "Hindi Ấn độ",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "hi",
        "data"      => [
            "home"          => "होम",
            "about_us"      => "हमारे बारे में",
            "wallpaper_theme"  => "वॉलपेपर थीम",
            "wallpaper_style"   => "वॉलपेपर शैली",
            "event"             => "आयोजन",
            "free_wallpaper"    => "मुफ्त वॉलपेपर",
            "support"           => "समर्थन",
            "connect_with_us"   => "हमसे जुड़ें",
            "table_of_contents" => "सामग्री",
            "photo_set"         => "फोटो सेट",
            "share"             => "साझा करें",
            "no_suitable_results_found" => "कोई उपयुक्त परिणाम नहीं मिला",
            "cart"              => "कार्ट",
            "your_cart_is_empty"    => "आपकी कार्ट खाली है",
            "continue_shopping"     => "खरीदारी जारी रखें",
            "phone_wallpaper"         => "फ़ोन वॉलपेपर ",
        ]
    ],
    "id"    => [
        "name"  => "Indonesia",
        "currency"  => "USD",
        "money_value"     => "1",
        "key"   => "id",
        "data"      => [
            "home"          => "Beranda",
            "about_us"      => "Tentang kami",
            "wallpaper_theme"  => "Tema Wallpaper",
            "wallpaper_style"   => "Gaya Wallpaper",
            "event"             => "Acara",
            "free_wallpaper"    => "Wallpaper Gratis",
            "support"           => "Dukungan",
            "connect_with_us"   => "Terhubung dengan kami",
            "table_of_contents" => "Daftar Isi",
            "photo_set"         => "Set foto",
            "share"             => "Berbagi",
            "no_suitable_results_found" => "Tidak ditemukan hasil yang sesuai",
            "cart"              => "Keranjang",
            "your_cart_is_empty"    => "Keranjang Anda kosong",
            "continue_shopping"     => "Lanjutkan berbelanja",
            "phone_wallpaper"         => "Wallpaper ponsel ",
        ]
    ]
];