<?php

return [
    "vi"    => [
        "name"      => "Việt",
        "currency"  => "VNĐ",
        "currency_code" => "đ",
        "money_value"     => "25000",
        "key"       => "vi",
        "data"      => [
            "home"              => "Trang chủ",
            "about_us"          => "Về chúng tôi",
            "wallpaper_theme"   => "Chủ đề Hình Nền",
            "wallpaper_style"   => "Phong cách Hình Nền",
            "event"             => "Sự kiện",
            "free_wallpaper"    => "Hình nền Miễn Phí",
            "support"           => "Hỗ trợ",
            "connect_with_us"   => "Kết nối với chúng tôi",
            "table_of_contents" => "Mục lục",
            "photo_set"         => "Bộ ảnh",
            "share"             => "Chia sẻ",
            "no_suitable_results_found" => "Không có kết quả phù hợp",
            "cart"              => "Giỏ hàng",
            "your_cart_is_empty"    => "Giỏ hàng của bạn trống",
            "continue_shopping" => "Tiếp tục mua sắm",
            "phone_wallpaper"   => "Hình nền điện thoại ",
            "full_set"          => "Trọn bộ",
            "image"             => "Ảnh",
            "options"           => "Tùy chọn",
            "product_description"   => "<div>Thêm một chút màu sắc và phong cách độc đáo vào chiếc điện thoại xinh xắn của bạn với Bộ hình nền điện thoại tuyệt đẹp này.</div>
                                            <ul>
                                                <li>Độ phân giải: 1440x3360</li>
                                                <li>Tương thích tất cả màn hình điện thoại.</li>
                                            </ul>
                                            <div>Tải xuống áp dụng ngay trên màn hình điện thoại của bạn để cảm nhận nhé!</div>",
            "product_guide_after_payment"   => '<div>Sau khi thanh toán bằng <span class="highLight">Momo /Zalopay</span>, Bạn sẽ nhận được link ảnh gốc để có thể tải xuống và sử dụng.</div>',
            "suggestions_for_you"   => "Gợi ý cho bạn!",
            "each_image"        => "Từng ảnh",
            "each_set"          => "Từng bộ",
            'propose' => 'Đề xuất',
            'favourite' => 'Yêu thích',
            'newest' => 'Mới nhất',
            'oldest' => 'Cũ nhất',
            'browse_by' => 'Duyệt theo ',
            'sort_by' => 'Sắp xếp theo ',
            'filter_by' => 'Lọc theo ',
            'advanced_filter' => 'Bộ lọc nâng cao',
            'all' => 'Tất cả',
            'added_to_cart' => 'Đã thêm vào giỏ hàng!',
            'view_cart' => 'Xem Giỏ Hàng',
            'add_to_cart' => 'Thêm Giỏ Hàng',
            'buy_now' => 'Mua Ngay',
            'undefined' => 'Không xác định',
            'total' => 'Tổng',
            'remove_item_in_cart' => 'Xóa sản phẩm trong Giỏ Hàng',
            'product_list' => 'Danh sách Sản Phẩm',
            'product' => 'Sản Phẩm',
            'unit_price' => 'Đơn Giá',
            'total_price' => 'Thành Tiền',
            'payment' => 'Thanh Toán',
            'information' => 'Thông Tin',
            'email_prompt' => 'Nếu nhập Email bạn sẽ được gửi thêm một bản để lưu trữ.',
            'email_receive' => 'Email dùng nhận ảnh',
            'payment_method' => 'Hình thức Thanh Toán',
            'fee' => 'Phí',
            'payment_fee' => 'Phí thanh toán',
        ]
    ],
    "en"    => [
        "name"  => "Anh",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "en",
        "data"      => [
            "home"          => "Home",
            "about_us"      => "About us",
            "wallpaper_theme"  => "Wallpaper Theme",
            "wallpaper_style"   => "Wallpaper Style",
            "event"             => "Event",
            "free_wallpaper"    => "Free Wallpaper",
            "support"           => "Support",
            "connect_with_us"   => "Connect with us",
            "table_of_contents" => "Table of Contents",
            "photo_set"         => "Photo set",
            "share"             => "Share",
            "no_suitable_results_found" => "No suitable results found",
            "cart"              => "Cart",
            "your_cart_is_empty"    => "Your cart is empty",
            "continue_shopping"     => "Continue shopping",
            "phone_wallpaper"         => "Phone Wallpaper ",
            "full_set"          => "Full set",
            "image"             => "Image",
            "options"           => "Options",
            "product_description"   => "<div>Add some color and unique style to your cute phone with this beautiful phone wallpaper set.</div>
                                            <ul>
                                                <li>Resolution: 1440x3360</li>
                                                <li>Compatible with all phone screens.</li>
                                            </ul>
                                            <div>Download and apply it directly to your phone screen to experience it!</div>",
            "product_guide_after_payment"   => '<div>After payment with <span class="highLight">Momo /Zalopay</span>, you will receive the original image link for downloading and using.</div>',
            "suggestions_for_you"   => "Suggestions for you!",
            "each_image"        => "Each image",
            "each_set"          => "Each set",
            'propose' => 'Propose',
            'favourite' => 'Favourite',
            'newest' => 'Newest',
            'oldest' => 'Oldest',
            'browse_by' => 'Browse by ',
            'sort_by' => 'Sort by ',
            'filter_by' => 'Filter by ',
            'advanced_filter' => 'Advanced Filter',
            'all' => 'All',
            'added_to_cart' => 'Added to Cart!',
            'view_cart' => 'View Cart',
            'add_to_cart' => 'Add to Cart',
            'buy_now' => 'Buy Now',
            'undefined' => 'Undefined',
            'total' => 'Total',
            'remove_item_in_cart' => 'Remove Item from Cart',
            'product_list' => 'Product List',
            'product' => 'Product',
            'unit_price' => 'Unit Price',
            'total_price' => 'Total Price',
            'payment' => 'Payment',
            'information' => 'Information',
            'email_prompt' => 'If you enter your email, you will receive an additional copy for storage.',
            'email_receive' => 'Email for receiving images',
            'payment_method' => 'Payment Method',
            'fee' => 'Fee',
            'payment_fee' => 'Payment Fee',
        ]
    ],
    "fr"    => [
        "name"  => "Pháp",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "fr",
        "data"      => [
            "home"              => "Accueil",
            "about_us"          => "À propos de nous",
            "wallpaper_theme"  => "Thème de fond d'écran",
            "wallpaper_style"   => "Style de fond d'écran",
            "event"             => "Événement",
            "free_wallpaper"    => "Fond d'écran gratuit",
            "support"           => "Support",
            "connect_with_us"       => "Connectez-vous avec nous",
            "table_of_contents"     => "Table des matières",
            "photo_set"             => "Série de photos",
            "share"                 => "Partager",
            "no_suitable_results_found" => "Aucun résultat approprié trouvé",
            "cart"                  => "Panier",
            "your_cart_is_empty"    => "Votre panier est vide",
            "continue_shopping"     => "Continuer les achats",
            "phone_wallpaper"       => "Fond d'écran de téléphone ",
            "full_set"              => "Ensemble complet",
            "image"                 => "Image",
            "options"               => "Options",
            "product_description"   => "<div>Ajoutez de la couleur et un style unique à votre téléphone mignon avec cet ensemble de superbes fonds d'écran pour téléphone.</div>
                                        <ul>
                                            <li>Résolution : 1440x3360</li>
                                            <li>Compatible avec tous les écrans de téléphone.</li>
                                        </ul>
                                        <div>Téléchargez-le et appliquez-le directement à l'écran de votre téléphone pour le ressentir !</div>",
            "product_guide_after_payment"   => '<div>Après le paiement avec <span class="highLight">Momo /Zalopay</span>, vous recevrez le lien de l\'image originale pour le téléchargement et l\'utilisation.</div>',
            "suggestions_for_you"   => "Suggestions pour vous!",
            "each_image"        => "Chaque image",
            "each_set"          => "Chaque ensemble",
            'propose' => 'Proposer',
            'favourite' => 'Favori',
            'newest' => 'Plus récent',
            'oldest' => 'Le plus ancien',
            'browse_by' => 'Parcourir par ',
            'sort_by' => 'Trier par ',
            'filter_by' => 'Filtrer par ',
            'advanced_filter' => 'Filtre avancé',
            'all' => 'Tous',
            'added_to_cart' => 'Ajouté au panier!',
            'view_cart' => 'Voir le Panier',
            'add_to_cart' => 'Ajouter au Panier',
            'buy_now' => 'Acheter Maintenant',
            'undefined' => 'Non défini',
            'total' => 'Total',
            'remove_item_in_cart' => 'Supprimer l\'article du panier',
            'product_list' => 'Liste des Produits',
            'product' => 'Produit',
            'unit_price' => 'Prix ​​unitaire',
            'total_price' => 'Prix ​​total',
            'payment' => 'Paiement',
            'information' => 'Information',
            'email_prompt' => 'Si vous saisissez votre adresse e-mail, vous recevrez une copie supplémentaire à des fins de stockage.',
            'email_receive' => 'E-mail pour recevoir des images',
            'payment_method' => 'Mode de paiement',
            'fee' => 'Frais',
            'payment_fee' => 'Frais de paiement',
        ]
    ],
    "es"    => [
        "name"  => "Tây Ban Nha",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "es",
        "data"      => [
            "home"          => "Inicio",
            "about_us"      => "Sobre nosotros",
            "wallpaper_theme"  => "Tema de fondo de pantalla",
            "wallpaper_style"   => "Estilo de fondo de pantalla",
            "event"             => "Evento",
            "free_wallpaper"    => "Fondo de pantalla gratis",
            "support"           => "Soporte",
            "connect_with_us"   => "Conéctate con nosotros",
            "table_of_contents" => "Tabla de contenido",
            "photo_set"         => "Conjunto de fotos",
            "share"             => "Compartir",
            "no_suitable_results_found" => "No se encontraron resultados adecuados",
            "cart"              => "Carrito",
            "your_cart_is_empty"    => "Tu carrito está vacío",
            "continue_shopping"     => "Continuar comprando",
            "phone_wallpaper"         => "Fondo de pantalla del teléfono ",
            "full_set"          => "Conjunto completo",
            "image"             => "Imagen",
            "options"           => "Opciones",
            "product_description"   => "<div>Agrega algo de color y estilo único a tu lindo teléfono con este hermoso conjunto de fondos de pantalla para teléfono.</div>
                                            <ul>
                                                <li>Resolución: 1440x3360</li>
                                                <li>Compatible con todas las pantallas de teléfono.</li>
                                            </ul>
                                            <div>¡Descárgalo y aplícalo directamente a la pantalla de tu teléfono para experimentarlo!</div>",
            "product_guide_after_payment"   => '<div>Después de realizar el pago con <span class="highLight">Momo /Zalopay</span>, recibirás el enlace de la imagen original para descargar y usar.</div>',
            "suggestions_for_you"   => "Sugerencias para ti!",
            "each_image"        => "Cada imagen",
            "each_set"          => "Cada conjunto",
            'propose' => 'Propuesta',
            'favourite' => 'Favorito',
            'newest' => 'El más nuevo',
            'oldest' => 'El más antiguo',
            'browse_by' => 'Navegar por ',
            'sort_by' => 'Ordenar por ',
            'filter_by' => 'Filtrar por ',
            'advanced_filter' => 'Filtro avanzado',
            'all' => 'Todos',
            'added_to_cart' => '¡Añadido al carrito!',
            'view_cart' => 'Ver Carrito',
            'add_to_cart' => 'Agregar al Carrito',
            'buy_now' => 'Comprar Ahora',
            'undefined' => 'No definido',
            'total' => 'Total',
            'remove_item_in_cart' => 'Eliminar artículo del carrito',
            'product_list' => 'Lista de Productos',
            'product' => 'Producto',
            'unit_price' => 'Precio Unitario',
            'total_price' => 'Precio Total',
            'payment' => 'Pago',
            'information' => 'Información',
            'email_prompt' => 'Si ingresas tu correo electrónico, recibirás una copia adicional para guardar.',
            'email_receive' => 'Correo electrónico para recibir imágenes',
            'payment_method' => 'Método de pago',
            'fee' => 'Tarifa',
            'payment_fee' => 'Tarifa de pago',
        ]
    ],
    "cn"    => [
        "name"  => "Trung Quốc (Quan Thoại)",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "cn",
        "data"      => [
            "home"          => "首页",
            "about_us"      => "关于我们",
            "wallpaper_theme"  => "壁纸主题",
            "wallpaper_style"   => "壁纸风格",
            "event"             => "事件",
            "free_wallpaper"    => "免费壁纸",
            "support"           => "支持",
            "connect_with_us"   => "与我们联系",
            "table_of_contents" => "目录",
            "photo_set"         => "照片集",
            "share"             => "分享",
            "no_suitable_results_found" => "没有找到合适的结果",
            "cart"              => "购物车",
            "your_cart_is_empty"    => "您的购物车是空的",
            "continue_shopping"     => "继续购物",
            "phone_wallpaper"         => "手机壁纸",
            "full_set"          => "全套",
            "image"             => "图片",
            "options"           => "选项",
            "product_description"   => "<div>为您可爱的手机增添一些色彩和独特的风格，使用这组美丽的手机壁纸。</div>
                                            <ul>
                                                <li>分辨率：1440x3360</li>
                                                <li>兼容所有手机屏幕。</li>
                                            </ul>
                                            <div>立即下载并应用于您的手机屏幕以体验它吧！</div>",
            "product_guide_after_payment"   => '<div>使用 <span class="highLight">Momo /Zalopay</span> 付款后，您将收到原始图片链接，可下载并使用。</div>',
            "suggestions_for_you"   => "给你的建议",
            "each_image"        => "每张图片",
            "each_set"          => "每套",
            'propose' => '提议',
            'favourite' => '喜爱',
            'newest' => '最新',
            'oldest' => '最老',
            'browse_by' => '按浏览',
            'sort_by' => '按排序',
            'filter_by' => '按过滤',
            'advanced_filter' => '高级过滤器',
            'all' => '全部',
            'added_to_cart' => '已添加到购物车!',
            'view_cart' => '查看购物车',
            'add_to_cart' => '添加到购物车',
            'buy_now' => '立即购买',
            'undefined' => '未定义',
            'total' => '总',
            'remove_item_in_cart' => '从购物车中删除项目',
            'product_list' => '产品列表',
            'product' => '产品',
            'unit_price' => '单价',
            'total_price' => '总价格',
            'payment' => '付款',
            'information' => '信息',
            'email_prompt' => '如果您输入您的电子邮件，您将收到额外的副本以供存储。',
            'email_receive' => '用于接收图像的电子邮件',
            'payment_method' => '支付方式',
            'fee' => '费用',
            'payment_fee' => '支付费用',
        ]
    ],
    "ru"    => [
        "name"  => "Nga",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "ru",
        "data"      => [
            "home"          => "Главная",
            "about_us"      => "О нас",
            "wallpaper_theme"  => "Тема обоев",
            "wallpaper_style"   => "Стиль обоев",
            "event"             => "Событие",
            "free_wallpaper"    => "Бесплатный обои",
            "support"           => "Поддержка",
            "connect_with_us"   => "Свяжитесь с нами",
            "table_of_contents" => "Оглавление",
            "photo_set"         => "Фотосет",
            "share"             => "Поделиться",
            "no_suitable_results_found" => "Подходящих результатов не найдено",
            "cart"              => "Корзина",
            "your_cart_is_empty"    => "Ваша корзина пуста",
            "continue_shopping"     => "Продолжить покупки",
            "phone_wallpaper"         => "Обои для телефона ",
            "full_set"          => "Полный комплект",
            "image"             => "Изображение",
            "options"           => "Варианты",
            "product_description"   => "<div>Добавьте немного цвета и уникального стиля на ваш милый телефон с этим красивым набором обоев для телефона.</div>
                                            <ul>
                                                <li>Разрешение: 1440x3360</li>
                                                <li>Совместимо со всеми телефонными экранами.</li>
                                            </ul>
                                            <div>Скачайте и примените его непосредственно на экран вашего телефона, чтобы ощутить его!</div>",
            "product_guide_after_payment"   => '<div>После оплаты через <span class="highLight">Momo /Zalopay</span>, вы получите ссылку на оригинальное изображение для загрузки и использования.</div>',
            "suggestions_for_you"   => "Предложения для вас",
            "each_image"        => "Каждый изображение",
            "each_set"          => "Каждый набор",
            'propose' => 'предлагать',
            'favourite' => 'любимый',
            'newest' => 'новейший',
            'oldest' => 'старейший',
            'browse_by' => 'Просматривать по ',
            'sort_by' => 'Сортировать по ',
            'filter_by' => 'Фильтровать по ',
            'advanced_filter' => 'Расширенный фильтр',
            'all' => 'Все',
            'added_to_cart' => 'Добавлено в корзину!',
            'view_cart' => 'Посмотреть Корзину',
            'add_to_cart' => 'Добавить в Корзину',
            'buy_now' => 'Купить Сейчас',
            'undefined' => 'Не определено',
            'total' => 'Общий',
            'remove_item_in_cart' => 'Удалить товар из корзины',
            'product_list' => 'Список продуктов',
            'product' => 'Продукт',
            'unit_price' => 'Цена за единицу',
            'total_price' => 'Итоговая цена',
            'payment' => 'Оплата',
            'information' => 'Информация',
            'email_prompt' => 'Если вы введете свой адрес электронной почты, вы получите дополнительную копию для хранения.',
            'email_receive' => 'Электронная почта для получения изображений',
            'payment_method' => 'Способ оплаты',
            'fee' => 'Плата',
            'payment_fee' => 'Плата за платеж',
        ]
    ],
    "ja"    => [
        "name"  => "Nhật Bản",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "ja",
        "data"      => [
            "home"          => "ホーム",
            "about_us"      => "私たちについて",
            "wallpaper_theme"  => "壁紙のテーマ",
            "wallpaper_style"   => "壁紙のスタイル",
            "event"             => "イベント",
            "free_wallpaper"    => "無料壁紙",
            "support"           => "サポート",
            "connect_with_us"   => "私たちとつながる",
            "table_of_contents" => "目次",
            "photo_set"         => "写真セット",
            "share"             => "共有",
            "no_suitable_results_found" => "適切な結果が見つかりませんでした",
            "cart"              => "カート",
            "your_cart_is_empty"    => "カートは空です",
            "continue_shopping"     => "買い物を続ける",
            "phone_wallpaper"         => "電話の壁紙",
            "full_set"          => "完全セット",
            "image"             => "画像",
            "options"           => "オプション",
            "product_description"   => "<div>かわいい携帯電話に色とユニークなスタイルを追加して、この美しい携帯電話用壁紙セットを使ってください。</div>
                                        <ul>
                                            <li>解像度：1440x3360</li>
                                            <li>すべての携帯電話の画面と互換性があります。</li>
                                        </ul>
                                        <div>ダウンロードして直接携帯電話の画面に適用して、体験してください！</div>",
            "product_guide_after_payment"   => '<div>Momo/Zalopayで支払いを完了すると、元の画像リンクが送られてきて、ダウンロードして使用できます。</div>',
            "suggestions_for_you"   => "あなたへの提案",
            "each_image"        => "各画像",
            "each_set"          => "各セット",
            'propose' => '提案する',
            'favourite' => 'お気に入り',
            'newest' => '最新',
            'oldest' => '最も古い',
            'browse_by' => '閲覧方法',
            'sort_by' => '並び替え方法',
            'filter_by' => 'フィルタリング方法',
            'advanced_filter' => '高度なフィルタ',
            'all' => 'すべて',
            'added_to_cart' => 'カートに追加されました！',
            'view_cart' => 'カートを見る',
            'add_to_cart' => 'カートに追加',
            'buy_now' => '今すぐ購入',
            'undefined' => '未定義',
            'total' => '合計',
            'remove_item_in_cart' => 'カートからアイテムを削除',
            'product_list' => '製品リスト',
            'product' => '製品',
            'unit_price' => '単価',
            'total_price' => '合計金額',
            'payment' => '支払い',
            'information' => '情報',
            'email_prompt' => 'メールアドレスを入力すると、ストレージ用に追加のコピーが送信されます。',
            'email_receive' => '画像を受け取るためのメール',
            'payment_method' => '支払い方法',
            'fee' => '手数料',
            'payment_fee' => '支払手数料',
        ]
    ],
    "ko"    => [
        "name"  => "Hàn Quốc",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "ko",
        "data"      => [
            "home"          => "홈",
            "about_us"      => "우리에 관하여",
            "wallpaper_theme"  => "벽지 테마",
            "wallpaper_style"   => "벽지 스타일",
            "event"             => "이벤트",
            "free_wallpaper"    => "무료 배경 화면",
            "support"           => "지원",
            "connect_with_us"   => "우리와 연락",
            "table_of_contents" => "목차",
            "photo_set"         => "사진 세트",
            "share"             => "공유",
            "no_suitable_results_found" => "적합한 결과를 찾을 수 없습니다",
            "cart"              => "카트",
            "your_cart_is_empty"    => "장바구니가 비어 있습니다",
            "continue_shopping"     => "쇼핑 계속하기",
            "phone_wallpaper"         => "휴대폰 배경화면 ",
            "full_set"          => "완전한 세트",
            "image"             => "이미지",
            "options"           => "옵션",
            "product_description"   => "<div>귀여운 핸드폰에 조금의 색상과 독특한 스타일을 더해주십시오. 이 아름다운 핸드폰 배경 화면 세트를 사용해보세요.</div>
                                            <ul>
                                                <li>해상도: 1440x3360</li>
                                                <li>모든 핸드폰 화면과 호환됩니다.</li>
                                            </ul>
                                            <div>다운로드하여 바로 핸드폰 화면에 적용하여 체험해보세요!</div>",
            "product_guide_after_payment"   => '<div><span class="highLight">Momo /Zalopay</span>로 결제한 후에, 원본 이미지 링크를 받아서 다운로드하고 사용할 수 있습니다.</div>',
            "suggestions_for_you"   => "당신을위한 제안",
            "each_image"        => "각 이미지",
            "each_set"          => "각 세트",
            'propose' => '제안하다',
            'favourite' => '좋아하는',
            'newest' => '최신',
            'oldest' => '가장 오래된',
            'browse_by' => '검색 ',
            'sort_by' => '정렬 기준 ',
            'filter_by' => '필터링 기준 ',
            'advanced_filter' => '고급 필터',
            'all' => '모두',
            'added_to_cart' => '장바구니에 추가되었습니다!',
            'view_cart' => '장바구니 보기',
            'add_to_cart' => '장바구니에 추가',
            'buy_now' => '지금 구매',
            'undefined' => '정의되지 않음',
            'total' => '총',
            'remove_item_in_cart' => '장바구니에서 상품 삭제',
            'product_list' => '제품 목록',
            'product' => '제품',
            'unit_price' => '단가',
            'total_price' => '총액',
            'payment' => '지불',
            'information' => '정보',
            'email_prompt' => '이메일을 입력하면 추가 복사본을 저장하려고합니다.',
            'email_receive' => '이미지를받을 이메일',
            'payment_method' => '지불 방법',
            'fee' => '수수료',
            'payment_fee' => '결제 수수료',
        ]
    ],
    "hi"    => [
        "name"  => "Hindi Ấn độ",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "hi",
        "data"      => [
            "home"          => "होम",
            "about_us"      => "हमारे बारे में",
            "wallpaper_theme"  => "वॉलपेपर थीम",
            "wallpaper_style"   => "वॉलपेपर शैली",
            "event"             => "आयोजन",
            "free_wallpaper"    => "मुफ्त वॉलपेपर",
            "support"           => "समर्थन",
            "connect_with_us"   => "हमसे जुड़ें",
            "table_of_contents" => "सामग्री",
            "photo_set"         => "फोटो सेट",
            "share"             => "साझा करें",
            "no_suitable_results_found" => "कोई उपयुक्त परिणाम नहीं मिला",
            "cart"              => "कार्ट",
            "your_cart_is_empty"    => "आपकी कार्ट खाली है",
            "continue_shopping"     => "खरीदारी जारी रखें",
            "phone_wallpaper"         => "फ़ोन वॉलपेपर ",
            "full_set"          => "पूरा सेट",
            "image"             => "छवि",
            "options"           => "विकल्प",
            "product_description"   => "<div>अपने प्यारे फोन में थोड़ा रंग और अनूठा शैली जोड़ें, इस सुंदर फोन वॉलपेपर सेट के साथ।</div>
                                            <ul>
                                                <li>रिज़ॉल्यूशन: 1440x3360</li>
                                                <li>सभी फोन स्क्रीन के साथ संगत है।</li>
                                            </ul>
                                            <div>इसे डाउनलोड करें और अपने फोन स्क्रीन पर सीधे लागू करें, इसे अनुभवित करें!</div>",
            "product_guide_after_payment"   => '<div>भुगतान के बाद <span class="highLight">Momo /Zalopay</span> के साथ, आपको मूल छवि लिंक प्राप्त होगा जिसे डाउनलोड और उपयोग कर सकते हैं।</div>',
            "suggestions_for_you"   => "आपके लिए सुझाव",
            "each_image"        => "प्रत्येक छवि",
            "each_set"          => "प्रत्येक सेट",
            'propose' => 'प्रस्ताव',
            'favourite' => 'पसंदीदा',
            'newest' => 'नवीनतम',
            'oldest' => 'सबसे पुराना',
            'browse_by' => 'ब्राउज़ करें ',
            'sort_by' => 'इसके अनुसार क्रमबद्ध करें ',
            'filter_by' => 'इसके अनुसार फ़िल्टर करें ',
            'advanced_filter' => 'उन्नत फ़िल्टर',
            'all' => 'सभी',
            'added_to_cart' => 'कार्ट में जोड़ा गया!',
            'view_cart' => 'कार्ट देखें',
            'add_to_cart' => 'कार्ट में डालें',
            'buy_now' => 'अभी खरीदें',
            'undefined' => 'अपरिभाषित',
            'total' => 'कुल',
            'remove_item_in_cart' => 'कार्ट से आइटम हटाएं',
            'product_list' => 'उत्पाद सूची',
            'product' => 'उत्पाद',
            'unit_price' => 'यूनिट मूल्य',
            'total_price' => 'कुल मूल्य',
            'payment' => 'भुगतान',
            'information' => 'जानकारी',
            'email_prompt' => 'यदि आप अपना ईमेल दर्ज करते हैं, तो आपको भंडारण के लिए एक अतिरिक्त प्रतिलिपि प्राप्त होगी।',
            'email_receive' => 'छवियों को प्राप्त करने के लिए ईमेल',
            'payment_method' => 'भुगतान का तरीका',
            'fee' => 'शुल्क',
            'payment_fee' => 'भुगतान शुल्क',
        ]
    ],
    "id"    => [
        "name"  => "Indonesia",
        "currency"  => "USD",
        "currency_code" => "$",
        "money_value"     => "1",
        "key"   => "id",
        "data"      => [
            "home"          => "Beranda",
            "about_us"      => "Tentang kami",
            "wallpaper_theme"  => "Tema Wallpaper",
            "wallpaper_style"   => "Gaya Wallpaper",
            "event"             => "Acara",
            "free_wallpaper"    => "Wallpaper Gratis",
            "support"           => "Dukungan",
            "connect_with_us"   => "Terhubung dengan kami",
            "table_of_contents" => "Daftar Isi",
            "photo_set"         => "Set foto",
            "share"             => "Berbagi",
            "no_suitable_results_found" => "Tidak ditemukan hasil yang sesuai",
            "cart"              => "Keranjang",
            "your_cart_is_empty"    => "Keranjang Anda kosong",
            "continue_shopping"     => "Lanjutkan berbelanja",
            "phone_wallpaper"         => "Wallpaper ponsel ",
            "full_set"          => "Set lengkap",
            "image"             => "Gambar",
            "options"           => "Pilihan",
            "product_description"   => "<div>Tambahkan sedikit warna dan gaya unik ke ponsel lucu Anda dengan set wallpaper ponsel yang indah ini.</div>
                                            <ul>
                                                <li>Resolusi: 1440x3360</li>
                                                <li>Kompatibel dengan semua layar ponsel.</li>
                                            </ul>
                                            <div>Unduh dan terapkan langsung ke layar ponsel Anda untuk merasakannya!</div>",
            "product_guide_after_payment"   => '<div>Setelah pembayaran dengan <span class="highLight">Momo /Zalopay</span>, Anda akan menerima tautan gambar asli untuk diunduh dan digunakan.</div>',
            "suggestions_for_you"   => "Saran untuk Anda",
            "each_image"        => "Setiap gambar",
            "each_set"          => "Setiap set",
            'propose' => 'Usul',
            'favourite' => 'Favorit',
            'newest' => 'Terbaru',
            'oldest' => 'Tertua',
            'browse_by' => 'Jelajahi dengan ',
            'sort_by' => 'Urutkan berdasarkan ',
            'filter_by' => 'Saring berdasarkan ',
            'advanced_filter' => 'Filter Lanjutan',
            'all' => 'Semua',
            'added_to_cart' => 'Ditambahkan ke Keranjang!',
            'view_cart' => 'Lihat Keranjang',
            'add_to_cart' => 'Tambahkan ke Keranjang',
            'buy_now' => 'Beli Sekarang',
            'undefined' => 'Tidak terdefinisi',
            'total' => 'Total',
            'remove_item_in_cart' => 'Hapus Barang dari Keranjang',
            'product_list' => 'Daftar Produk',
            'product' => 'Produk',
            'unit_price' => 'Harga Satuan',
            'total_price' => 'Total Harga',
            'payment' => 'Pembayaran',
            'information' => 'Informasi',
            'email_prompt' => 'Jika Anda memasukkan email Anda, Anda akan menerima salinan tambahan untuk penyimpanan.',
            'email_receive' => 'Email untuk menerima gambar',
            'payment_method' => 'Metode Pembayaran',
            'fee' => 'Biaya',
            'payment_fee' => 'Biaya Pembayaran',
        ]
    ]
];